#!/bin/bash
export black="\[\033[0;38;5;0m\]"
export red="\[\033[0;38;5;1m\]"
export brown="\[\033[0;38;5;130m\]"
export green="\[\033[0;38;5;2m\]"
export yellow='\[\e[1;33m\]'
export blue="\[\033[0;38;5;4m\]"
export bblue="\[\033[0;38;5;12m\]"
export magenta="\[\033[0;38;5;55m\]"
export cyan="\[\033[0;38;5;6m\]"
export white="\[\033[0;38;5;7m\]" 
export coldblue="\[\033[0;38;5;33m\]"
export smoothblue="\[\033[0;38;5;111m\]"
export iceblue="\[\033[0;38;5;45m\]"
export turqoise="\[\033[0;38;5;50m\]"
export smoothgreen="\[\033[0;38;5;42m\]"
### TODO: Escape CAPS color values with \[ \] then update prompt
#   This to prevent line-wrapping wonkiness
export NO_COLOR="\[\033\e[0m\]" # No Color
export COLOR_WHITE='\e[1;37m'
export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_GRAY='\e[0;30m'
export COLOR_LIGHT_GRAY='\e[0;37m'


case "$TERM" in
xterm*)
    PS1="${cyan}┌─(${NO_COLOR}\u@\h${cyan})─\
(${NO_COLOR}\w${cyan})-(${NO_COLOR}\$(date \"+%Y-%m-%d %H:%M:%S\")\
${cyan})┐\n${cyan}└─(${yellow}\
\$(parse_git_branch)${cyan})─>${NO_COLOR}"
    ;;
screen*)
    PS1="\[${COLOR_YELLOW}\]┌─(${NO_COLOR}\u@\h\[${COLOR_YELLOW}\])─\
(${NO_COLOR}\w\[${COLOR_YELLOW}\])-(${NO_COLOR}\$(date \"+%Y-%m-%d %H:%M:%S\")\
\[${COLOR_YELLOW}\])┐\n\[${COLOR_YELLOW}\]└─(${NO_COLOR}\
\$(parse_git_branch)\[${COLOR_YELLOW}\])─>${NO_COLOR}"
#    PS1="\[${COLOR_YELLOW}\]┌─(\[${NO_COLOR}\]\u@\h\[${COLOR_YELLOW}\])─\
#(\[${NO_COLOR}\]\w\[${COLOR_YELLOW}\])-(\[${NO_COLOR}\]\$(date \"+%Y-%m-%d %H:%M:%S\")\
#\[${COLOR_YELLOW}\])┐\n\[${COLOR_YELLOW}\]└─(\[${NO_COLOR}\]\
#\$(parse_git_branch)\[${COLOR_YELLOW}\])─>\[${NO_COLOR}\]"
    ;;    
    *)
    PS1="\[${COLOR_LIGHT_GREEN}\]┌─(${NO_COLOR}\u@\h\[${COLOR_LIGHT_GREEN}\])─\
(${NO_COLOR}\w\[${COLOR_LIGHT_GREEN}\])-(${NO_COLOR}\$(date \"+%Y-%m-%d %H:%M:%S\")\
\[${COLOR_LIGHT_GREEN}\])┐\n└─(${NO_COLOR}\
\$(parse_git_branch)\[${COLOR_LIGHT_GREEN}\])─>${NO_COLOR}"
    ;;
esac
